/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-08-23 02:29:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no\" name=\"viewport\">\r\n");
      out.write("  <title>Register &mdash; Stisla</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- General CSS Files -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.2/css/all.css\" integrity=\"sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("  <!-- CSS Libraries -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../node_modules/selectric/public/selectric.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../assets/css/style.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../assets/css/components.css\">\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"app\">\r\n");
      out.write("    <section class=\"section\">\r\n");
      out.write("      <div class=\"container mt-5\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 col-xl-8 offset-xl-2\">\r\n");
      out.write("            <div class=\"login-brand\">\r\n");
      out.write("              <img src=\"../assets/img/stisla-fill.svg\" alt=\"logo\" width=\"100\" class=\"shadow-light rounded-circle\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card card-primary\">\r\n");
      out.write("              <div class=\"card-header\"><h4>회원가입</h4></div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"card-body\">\r\n");
      out.write("                <form method=\"POST\" action=\"joinCon.do\" id=\"MForm\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"form-group col-6\">\r\n");
      out.write("                      <label for=\"first_name\">이름</label>\r\n");
      out.write("                      <input id=\"first_name\" type=\"text\" class=\"form-control\" name=\"name\"  autofocus>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group col-6\">\r\n");
      out.write("                      <label for=\"last_name\">전화번호</label>\r\n");
      out.write("                      <input id=\"last_name\" type=\"text\" class=\"form-control\" name=\"tel\" >\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"email\">이메일</label>\r\n");
      out.write("                    <input id=\"email\" type=\"email\" class=\"form-control\" name=\"email\" >\r\n");
      out.write("                    <div class=\"invalid-feedback\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"form-group col-6\">\r\n");
      out.write("                      <label for=\"password\" class=\"d-block\">비밀번호</label>\r\n");
      out.write("                      <input id=\"password\" type=\"password\" class=\"form-control pwstrength\" data-indicator=\"pwindicator\" name=\"pw\" >\r\n");
      out.write("                      <div id=\"pwindicator\" class=\"pwindicator\">\r\n");
      out.write("                        <div class=\"bar\"></div>\r\n");
      out.write("                        <div class=\"label\"></div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group col-6\">\r\n");
      out.write("                      <label for=\"password2\" class=\"d-block\">비밀번호 확인</label>\r\n");
      out.write("                      <input id=\"password2\" type=\"password\" class=\"form-control\" name=\"password-confirm\" >\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <!-- <div class=\"form-divider\">\r\n");
      out.write("                    Your Home\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"form-group col-6\">\r\n");
      out.write("                      <label>Country</label>\r\n");
      out.write("                      <select class=\"form-control selectric\">\r\n");
      out.write("                        <option>Indonesia</option>\r\n");
      out.write("                        <option>Palestine</option>\r\n");
      out.write("                        <option>Syria</option>\r\n");
      out.write("                        <option>Malaysia</option>\r\n");
      out.write("                        <option>Thailand</option>\r\n");
      out.write("                      </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group col-6\">\r\n");
      out.write("                      <label>Province</label>\r\n");
      out.write("                      <select class=\"form-control selectric\">\r\n");
      out.write("                        <option>West Java</option>\r\n");
      out.write("                        <option>East Java</option>\r\n");
      out.write("                      </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"form-group col-6\">\r\n");
      out.write("                      <label>City</label>\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group col-6\">\r\n");
      out.write("                      <label>Postal Code</label>\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <div class=\"custom-control custom-checkbox\">\r\n");
      out.write("                      <input type=\"checkbox\" name=\"agree\" class=\"custom-control-input\" id=\"agree\">\r\n");
      out.write("                      <label class=\"custom-control-label\" for=\"agree\">I agree with the terms and conditions</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div> -->\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"form-group\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary btn-lg btn-block\">\r\n");
      out.write("                      회원가입\r\n");
      out.write("                    </button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </form>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"simple-footer\">\r\n");
      out.write("              Copyright &copy; Stisla 2021\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- General JS Scripts -->\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.3.1.min.js\" integrity=\"sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js\"></script>\r\n");
      out.write("  <script src=\"../assets/js/stisla.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- JS Libraies -->\r\n");
      out.write("  <script src=\"../node_modules/jquery-pwstrength/jquery.pwstrength.min.js\"></script>\r\n");
      out.write("  <script src=\"../node_modules/selectric/public/jquery.selectric.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template JS File -->\r\n");
      out.write("  <script src=\"../assets/js/scripts.js\"></script>\r\n");
      out.write("  <script src=\"../assets/js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Page Specific JS File -->\r\n");
      out.write("  <script src=\"../assets/js/page/auth-register.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <!-- 비밀번호 일치 불일치 판별 -->\r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("   \r\n");
      out.write("   $(function(){// 웹 페이지 로드가 다 되면 자바스크립트를 실행시켜주는 이벤트함수 \r\n");
      out.write("	            //자바스크립트를 안정적으로 동작시키기 위해서 \r\n");
      out.write("\r\n");
      out.write("		    $('#MForm').submit(function(event){\r\n");
      out.write("			   \r\n");
      out.write("			  \r\n");
      out.write("			   \r\n");
      out.write("			   \r\n");
      out.write("			   var pw1 = $('#password').val(); //비밀번호\r\n");
      out.write("			   var pw2 = $('#password2').val(); //비밀번호 확인\r\n");
      out.write("			   \r\n");
      out.write("\r\n");
      out.write("			   	if( pw1 != pw2){ //비밀번호가 일치하지 않을때\r\n");
      out.write("			   		alert(\"비밀번호가 일치 하지 않습니다\");\r\n");
      out.write("			   	    //submit 처리 되는 것을 막아야함 \r\n");
      out.write("			   		event.preventDefault(); \r\n");
      out.write("			   		return; //$('#MForm').submit() 기능 종료\r\n");
      out.write("			   	}\r\n");
      out.write("\r\n");
      out.write("			   	$('form').submit();\r\n");
      out.write("		    }); \r\n");
      out.write("		    \r\n");
      out.write("		  \r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   /*  function pwCheck{\r\n");
      out.write("    \r\n");
      out.write("    	\r\n");
      out.write("    	var p1 = document.getElementById('password').value;\r\n");
      out.write("    	var p2 = document.getElementById('password2').value;\r\n");
      out.write("    	\r\n");
      out.write("    	if( p1 != p2){\r\n");
      out.write("    		alert(\"비밀번호가 일치 하지 않습니다\");\r\n");
      out.write("    		return false;\r\n");
      out.write("    	}else{\r\n");
      out.write("    		alert(\"비밀번호가 일치 합니다\");\r\n");
      out.write("    		return true;\r\n");
      out.write("    	}\r\n");
      out.write("    } */\r\n");
      out.write("  </script> \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
