/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-08-27 06:10:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.StockBestDAO;
import model.StockBestDTO;
import model.StockTermsDTO;
import java.util.ArrayList;
import model.MemberDTO;

public final class StockBest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/pages/Sidebar.jsp", Long.valueOf(1629969128982L));
    _jspx_dependants.put("/pages/Footer.jsp", Long.valueOf(1630022666676L));
    _jspx_dependants.put("/pages/Header.jsp", Long.valueOf(1629970215639L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.StockTermsDTO");
    _jspx_imports_classes.add("model.StockBestDTO");
    _jspx_imports_classes.add("model.MemberDTO");
    _jspx_imports_classes.add("model.StockBestDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");


StockBestDAO dao = new StockBestDAO(); // 국내종목 실시간 BEST DAO
ArrayList<StockBestDTO> list = new ArrayList<StockBestDTO>(); //ArrayList생성
list=dao.select();

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no\" name=\"viewport\">\r\n");
      out.write("  <title>Tickets &mdash; Stisla</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- General CSS Files -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.2/css/all.css\" integrity=\"sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("  <!-- CSS Libraries -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../node_modules/summernote/dist/summernote-bs4.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../node_modules/chocolat/dist/css/chocolat.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../assets/css/style.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../assets/css/components.css\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div id=\"app\">\r\n");
      out.write("    <div class=\"main-wrapper\">\r\n");
      out.write("      <div class=\"navbar-bg\"></div>\r\n");
      out.write("      \r\n");
      out.write("      <!-- header -->\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
 MemberDTO member = (MemberDTO)session.getAttribute("member");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no\" name=\"viewport\">\r\n");
      out.write("  <title>General Dashboard &mdash; Stisla</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- General CSS Files -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.2/css/all.css\" integrity=\"sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("  <!-- CSS Libraries -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../node_modules/jqvmap/dist/jqvmap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../node_modules/weathericons/css/weather-icons.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../node_modules/weathericons/css/weather-icons-wind.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../node_modules/summernote/dist/summernote-bs4.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../assets/css/style.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../assets/css/components.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- icon fontawesome -->\r\n");
      out.write("  <script src=\"https://use.fontawesome.com/releases/v5.2.0/js/all.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("      <!-- header -->\r\n");
      out.write("      <nav class=\"navbar navbar-expand-lg main-navbar\">\r\n");
      out.write("        <form action=\"StockSearchListCon.do\" class=\"form-inline mr-auto\">\r\n");
      out.write("          <ul class=\"navbar-nav mr-3\">\r\n");
      out.write("            <li><a href=\"#\" data-toggle=\"sidebar\" class=\"nav-link nav-link-lg\"><i class=\"fas fa-bars\"></i></a></li>\r\n");
      out.write("            <li><a href=\"#\" data-toggle=\"search\" class=\"nav-link nav-link-lg d-sm-none\"><i class=\"fas fa-search\"></i></a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <div class=\"search-element\">\r\n");
      out.write("            <input class=\"form-control\" name=\"searchtext\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\" data-width=\"250\">\r\n");
      out.write("            <button class=\"btn\" type=\"submit\"><i class=\"fas fa-search\"></i></button>\r\n");
      out.write("            <div class=\"search-backdrop\"></div>\r\n");
      out.write("            <div class=\"search-result\">\r\n");
      out.write("              <div class=\"search-header\">\r\n");
      out.write("                Histories\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"search-item\">\r\n");
      out.write("                <a href=\"#\">삼성전자</a>\r\n");
      out.write("                <a href=\"#\" class=\"search-close\"><i class=\"fas fa-times\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"search-item\">\r\n");
      out.write("                <a href=\"#\">sk하이닉스</a>\r\n");
      out.write("                <a href=\"#\" class=\"search-close\"><i class=\"fas fa-times\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"search-item\">\r\n");
      out.write("                <a href=\"#\">셀트리온</a>\r\n");
      out.write("                <a href=\"#\" class=\"search-close\"><i class=\"fas fa-times\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"search-header\">\r\n");
      out.write("                Result\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"search-item\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                  <img class=\"mr-3 rounded\" width=\"30\" src=\"../assets/img/products/product-3-50.png\" alt=\"product\">\r\n");
      out.write("                  oPhone S9 Limited Edition\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"search-item\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                  <img class=\"mr-3 rounded\" width=\"30\" src=\"../assets/img/products/product-2-50.png\" alt=\"product\">\r\n");
      out.write("                  Drone X2 New Gen-7\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"search-item\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                  <img class=\"mr-3 rounded\" width=\"30\" src=\"../assets/img/products/product-1-50.png\" alt=\"product\">\r\n");
      out.write("                  Headphone Blitz\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"search-header\">\r\n");
      out.write("                Projects\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"search-item\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                  <div class=\"search-icon bg-danger text-white mr-3\">\r\n");
      out.write("                    <i class=\"fas fa-code\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  Stisla Admin Template\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"search-item\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                  <div class=\"search-icon bg-primary text-white mr-3\">\r\n");
      out.write("                    <i class=\"fas fa-laptop\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  Create a new Homepage Design\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        <ul class=\"navbar-nav navbar-right\">\r\n");
      out.write("          <li class=\"dropdown dropdown-list-toggle\"><a href=\"#\" data-toggle=\"dropdown\" class=\"nav-link nav-link-lg message-toggle beep\"><i class=\"far fa-envelope\"></i></a>\r\n");
      out.write("            <div class=\"dropdown-menu dropdown-list dropdown-menu-right\">\r\n");
      out.write("              <div class=\"dropdown-header\">Messages\r\n");
      out.write("                <div class=\"float-right\">\r\n");
      out.write("                  <a href=\"#\">Mark All As Read</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"dropdown-list-content dropdown-list-message\">\r\n");
      out.write("                <a href=\"#\" class=\"dropdown-item dropdown-item-unread\">\r\n");
      out.write("                  <div class=\"dropdown-item-avatar\">\r\n");
      out.write("                    <img alt=\"image\" src=\"../assets/img/avatar/avatar-1.png\" class=\"rounded-circle\">\r\n");
      out.write("                    <div class=\"is-online\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"dropdown-item-desc\">\r\n");
      out.write("                    <b>Kusnaedi</b>\r\n");
      out.write("                    <p>Hello, Bro!</p>\r\n");
      out.write("                    <div class=\"time\">10 Hours Ago</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"dropdown-item dropdown-item-unread\">\r\n");
      out.write("                  <div class=\"dropdown-item-avatar\">\r\n");
      out.write("                    <img alt=\"image\" src=\"../assets/img/avatar/avatar-2.png\" class=\"rounded-circle\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"dropdown-item-desc\">\r\n");
      out.write("                    <b>Dedik Sugiharto</b>\r\n");
      out.write("                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>\r\n");
      out.write("                    <div class=\"time\">12 Hours Ago</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"dropdown-item dropdown-item-unread\">\r\n");
      out.write("                  <div class=\"dropdown-item-avatar\">\r\n");
      out.write("                    <img alt=\"image\" src=\"../assets/img/avatar/avatar-3.png\" class=\"rounded-circle\">\r\n");
      out.write("                    <div class=\"is-online\"></div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"dropdown-item-desc\">\r\n");
      out.write("                    <b>Agung Ardiansyah</b>\r\n");
      out.write("                    <p>Sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n");
      out.write("                    <div class=\"time\">12 Hours Ago</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("                  <div class=\"dropdown-item-avatar\">\r\n");
      out.write("                    <img alt=\"image\" src=\"../assets/img/avatar/avatar-4.png\" class=\"rounded-circle\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"dropdown-item-desc\">\r\n");
      out.write("                    <b>Ardian Rahardiansyah</b>\r\n");
      out.write("                    <p>Duis aute irure dolor in reprehenderit in voluptate velit ess</p>\r\n");
      out.write("                    <div class=\"time\">16 Hours Ago</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("                  <div class=\"dropdown-item-avatar\">\r\n");
      out.write("                    <img alt=\"image\" src=\"../assets/img/avatar/avatar-5.png\" class=\"rounded-circle\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"dropdown-item-desc\">\r\n");
      out.write("                    <b>Alfa Zulkarnain</b>\r\n");
      out.write("                    <p>Exercitation ullamco laboris nisi ut aliquip ex ea commodo</p>\r\n");
      out.write("                    <div class=\"time\">Yesterday</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"dropdown-footer text-center\">\r\n");
      out.write("                <a href=\"#\">View All <i class=\"fas fa-chevron-right\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"dropdown dropdown-list-toggle\"><a href=\"#\" data-toggle=\"dropdown\" class=\"nav-link notification-toggle nav-link-lg beep\"><i class=\"far fa-bell\"></i></a>\r\n");
      out.write("            <div class=\"dropdown-menu dropdown-list dropdown-menu-right\">\r\n");
      out.write("              <div class=\"dropdown-header\">Notifications\r\n");
      out.write("                <div class=\"float-right\">\r\n");
      out.write("                  <a href=\"#\">Mark All As Read</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"dropdown-list-content dropdown-list-icons\">\r\n");
      out.write("                <a href=\"#\" class=\"dropdown-item dropdown-item-unread\">\r\n");
      out.write("                  <div class=\"dropdown-item-icon bg-primary text-white\">\r\n");
      out.write("                    <i class=\"fas fa-code\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"dropdown-item-desc\">\r\n");
      out.write("                    Template update is available now!\r\n");
      out.write("                    <div class=\"time text-primary\">2 Min Ago</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("                  <div class=\"dropdown-item-icon bg-info text-white\">\r\n");
      out.write("                    <i class=\"far fa-user\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"dropdown-item-desc\">\r\n");
      out.write("                    <b>You</b> and <b>Dedik Sugiharto</b> are now friends\r\n");
      out.write("                    <div class=\"time\">10 Hours Ago</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("                  <div class=\"dropdown-item-icon bg-success text-white\">\r\n");
      out.write("                    <i class=\"fas fa-check\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"dropdown-item-desc\">\r\n");
      out.write("                    <b>Kusnaedi</b> has moved task <b>Fix bug header</b> to <b>Done</b>\r\n");
      out.write("                    <div class=\"time\">12 Hours Ago</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("                  <div class=\"dropdown-item-icon bg-danger text-white\">\r\n");
      out.write("                    <i class=\"fas fa-exclamation-triangle\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"dropdown-item-desc\">\r\n");
      out.write("                    Low disk space. Let's clean it!\r\n");
      out.write("                    <div class=\"time\">17 Hours Ago</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("                  <div class=\"dropdown-item-icon bg-info text-white\">\r\n");
      out.write("                    <i class=\"fas fa-bell\"></i>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"dropdown-item-desc\">\r\n");
      out.write("                    Welcome to Stisla template!\r\n");
      out.write("                    <div class=\"time\">Yesterday</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"dropdown-footer text-center\">\r\n");
      out.write("                <a href=\"#\">View All <i class=\"fas fa-chevron-right\"></i></a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"dropdown\"><a href=\"#\" data-toggle=\"dropdown\" class=\"nav-link dropdown-toggle nav-link-lg nav-link-user\">\r\n");
      out.write("            <img alt=\"image\" src=\"../assets/img/avatar/avatar-1.png\" class=\"rounded-circle mr-1\">\r\n");
      out.write("            <div class=\"d-sm-none d-lg-inline-block\">Hi</div></a>\r\n");
      out.write("            <div class=\"dropdown-menu dropdown-menu-right\">\r\n");
      out.write("              <div class=\"dropdown-title\">Logged in 5 min ago</div>\r\n");
      out.write("              <a href=\"features-profile.html\" class=\"dropdown-item has-icon\">\r\n");
      out.write("                <i class=\"far fa-user\"></i> Profile\r\n");
      out.write("              </a>\r\n");
      out.write("              <a href=\"Update.jsp\" class=\"dropdown-item has-icon\">\r\n");
      out.write("                <i class=\"fas fa-bolt\"></i> 회원정보수정\r\n");
      out.write("              </a>\r\n");
      out.write("              <a href=\"features-settings.html\" class=\"dropdown-item has-icon\">\r\n");
      out.write("                <i class=\"fas fa-cog\"></i> Settings\r\n");
      out.write("              </a>\r\n");
      out.write("              <div class=\"dropdown-divider\"></div>\r\n");
      out.write("              ");
if(member != null){ 
      out.write("\r\n");
      out.write("              <a href=\"Logout.jsp\" class=\"dropdown-item has-icon text-danger\">\r\n");
      out.write("                <i class=\"fas fa-sign-out-alt\"></i> Logout\r\n");
      out.write("              </a>\r\n");
      out.write("              ");
} 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- General JS Scripts -->\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.3.1.min.js\" integrity=\"sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js\"></script>\r\n");
      out.write("  <script src=\"../assets/js/stisla.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- JS Libraies -->\r\n");
      out.write("  <script src=\"../node_modules/simpleweather/jquery.simpleWeather.min.js\"></script>\r\n");
      out.write("  <script src=\"../node_modules/chart.js/dist/Chart.min.js\"></script>\r\n");
      out.write("  <script src=\"../node_modules/jqvmap/dist/jquery.vmap.min.js\"></script>\r\n");
      out.write("  <script src=\"../node_modules/jqvmap/dist/maps/jquery.vmap.world.js\"></script>\r\n");
      out.write("  <script src=\"../node_modules/summernote/dist/summernote-bs4.js\"></script>\r\n");
      out.write("  <script src=\"../node_modules/chocolat/dist/js/jquery.chocolat.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template JS File -->\r\n");
      out.write("  <script src=\"../assets/js/scripts.js\"></script>\r\n");
      out.write("  <script src=\"../assets/js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Page Specific JS File -->\r\n");
      out.write("  <script src=\"../assets/js/page/index-0.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <!-- Sidebar -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no\" name=\"viewport\">\r\n");
      out.write("  <title>General Dashboard &mdash; Stisla</title>\r\n");
      out.write("\r\n");
      out.write("  <!-- General CSS Files -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.2/css/all.css\" integrity=\"sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("  <!-- CSS Libraries -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../node_modules/jqvmap/dist/jqvmap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../node_modules/weathericons/css/weather-icons.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../node_modules/weathericons/css/weather-icons-wind.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../node_modules/summernote/dist/summernote-bs4.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../assets/css/style.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../assets/css/components.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- icon fontawesome -->\r\n");
      out.write("  <script src=\"https://use.fontawesome.com/releases/v5.2.0/js/all.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("      <!-- Start sidebar -->\r\n");
      out.write("      <div class=\"main-sidebar\">\r\n");
      out.write("        <aside id=\"sidebar-wrapper\">\r\n");
      out.write("          <div class=\"sidebar-brand\">\r\n");
      out.write("            <a href=\"Main.jsp\">어플이름</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"sidebar-brand sidebar-brand-sm\">\r\n");
      out.write("            <a href=\"Main.jsp\">St</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <ul class=\"sidebar-menu\">\r\n");
      out.write("              <li class=\"menu-header\">Menu</li>\r\n");
      out.write("              <li class=\"nav-item dropdown\">\r\n");
      out.write("                <a href=\"Main_2.jsp\" class=\"nav-link\"> <span>홈</span></a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-header\">Stock Prediction</li>\r\n");
      out.write("              <li class=\"nav-item dropdown\">\r\n");
      out.write("                <a href=\"StockInfo.jsp\" class=\"nav-link\"> <span>주가정보</span></a>\r\n");
      out.write("                <a href=\"Predict.jsp\" class=\"nav-link\"> <span>주가예측</span></a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-header\">Information</li>\r\n");
      out.write("              <li class=\"nav-item dropdown\">\r\n");
      out.write("                <a href=\"Marketinfro.jsp\" class=\"nav-link\"> <span>시장정보</span></a>\r\n");
      out.write("                <a href=\"StockTerms.jsp\" class=\"nav-link\"> <span>주식용어</span></a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"menu-header\">myPages</li>\r\n");
      out.write("              <li class=\"nav-item dropdown\">\r\n");
      out.write("                <a href=\"Mypage.jsp\" class=\"nav-link\"> <span>회원정보수정</span></a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mt-4 mb-4 p-3 hide-sidebar-mini\">\r\n");
      out.write("              <a href=\"Logout.jsp\" class=\"btn btn-primary btn-lg btn-block btn-icon-split\">\r\n");
      out.write("                로그아웃\r\n");
      out.write("              </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </aside>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- End sidebar -->\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("  <!-- General JS Scripts -->\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.3.1.min.js\" integrity=\"sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js\"></script>\r\n");
      out.write("  <script src=\"../assets/js/stisla.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- JS Libraies -->\r\n");
      out.write("  <script src=\"../node_modules/simpleweather/jquery.simpleWeather.min.js\"></script>\r\n");
      out.write("  <script src=\"../node_modules/chart.js/dist/Chart.min.js\"></script>\r\n");
      out.write("  <script src=\"../node_modules/jqvmap/dist/jquery.vmap.min.js\"></script>\r\n");
      out.write("  <script src=\"../node_modules/jqvmap/dist/maps/jquery.vmap.world.js\"></script>\r\n");
      out.write("  <script src=\"../node_modules/summernote/dist/summernote-bs4.js\"></script>\r\n");
      out.write("  <script src=\"../node_modules/chocolat/dist/js/jquery.chocolat.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template JS File -->\r\n");
      out.write("  <script src=\"../assets/js/scripts.js\"></script>\r\n");
      out.write("  <script src=\"../assets/js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Page Specific JS File -->\r\n");
      out.write("  <script src=\"../assets/js/page/index-0.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("      <!-- Main Content -->\r\n");
      out.write("      <div class=\"main-content\">\r\n");
      out.write("        <section class=\"section\">\r\n");
      out.write("          <!-- <div class=\"section-header\">\r\n");
      out.write("            <h1>국내 종목 실시간Best</h1>\r\n");
      out.write("            <div class=\"section-header-breadcrumb\">\r\n");
      out.write("              <div class=\"breadcrumb-item active\"><a href=\"메인(index).html\">메인</a></div>\r\n");
      out.write("              <div class=\"breadcrumb-item\">Tickets</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div> -->\r\n");
      out.write("\r\n");
      out.write("          <div class=\"section-body\">\r\n");
      out.write("            <!-- <h2 class=\"section-title\">Help Your Customer</h2>\r\n");
      out.write("            <p class=\"section-lead\">\r\n");
      out.write("              Some customers need your help.\r\n");
      out.write("            </p> -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-12\">\r\n");
      out.write("                <div class=\"card\">\r\n");
      out.write("                  <div class=\"card-header\">\r\n");
      out.write("                    <h4>국내 종목 실시간Best</h4>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <form action=\"\" method=\"POST\">\r\n");
      out.write("                  <div id=\"best\" class=\"card-body\">\r\n");
      out.write("                    <table class=\"table\">\r\n");
      out.write("                      <thead>\r\n");
      out.write("                        <tr class=\"best_font\">\r\n");
      out.write("                          <th scope=\"col\">순위</th>\r\n");
      out.write("                          <th scope=\"col\">종목명</th>\r\n");
      out.write("                          <th scope=\"col\">현재가</th>\r\n");
      out.write("                          <th scope=\"col\">등락</th>\r\n");
      out.write("                          <th scope=\"col\">등락률</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                      </thead>\r\n");
      out.write("                      <tbody>\r\n");
      out.write("                      ");

                         for(int i=0; i<list.size();i++){
                      
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <th scope=\"row\">");
      out.print(i+1 );
      out.write("</th>\r\n");
      out.write("                          <td>");
      out.print(list.get(i).getJongMokName() );
      out.write("</td>\r\n");
      out.write("                          <td>");
      out.print(list.get(i).getNowPrice() );
      out.write("</td>\r\n");
      out.write("                          <td><div class=\"text-small text-muted\">");
      out.print(list.get(i).getUpDown() );
      out.write(" <i class=\"fas fa-caret-down text-danger\"></i></div></td>\r\n");
      out.write("                          <td>");
      out.print(list.get(i).getUpDownRate());
      out.write("%</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        ");
} 
      out.write("\r\n");
      out.write("                     <!--     <tr>\r\n");
      out.write("                          <th scope=\"row\">2</th>\r\n");
      out.write("                          <td>aaa</td>\r\n");
      out.write("                          <td>aaa</td>\r\n");
      out.write("                          <td><div class=\"text-small text-muted\">11 <i class=\"fas fa-caret-up text-danger\"></i></div></td>\r\n");
      out.write("                          <td>123</td>\r\n");
      out.write("                        </tr> -->\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("                      </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                  </div> \r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      	<!-- Footer -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("		<footer class=\"main-footer\">\r\n");
      out.write("        <div class=\"footer-left\">\r\n");
      out.write("          Copyright &copy; 2018 <div class=\"bullet\"></div> Design By <a href=\"https://nauval.in/\">Muhamad Nauval Azhar</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-left col-md-6\">\r\n");
      out.write("          -----------------------------------------------------------------\r\n");
      out.write("        </div>\r\n");
      out.write("        <p class=\"footer-right col-md-3\">\r\n");
      out.write("          Stock CM에서 제공하는 투자 정보는 고객의 투자 판단을 위한 단순 참고용입니다. \r\n");
      out.write("          모든 투자의 결정 및 최종 책임은 투자자 본인에게 있음을 알려드립니다. \r\n");
      out.write("        </p>\r\n");
      out.write("        <div class=\"footer-left col-md-6\">\r\n");
      out.write("          -----------------------------------------------------------------\r\n");
      out.write("        </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- General JS Scripts -->\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.3.1.min.js\" integrity=\"sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js\"></script>\r\n");
      out.write("  <script src=\"../assets/js/stisla.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- JS Libraies -->\r\n");
      out.write("  <script src=\"../node_modules/summernote/dist/summernote-bs4.js\"></script>\r\n");
      out.write("  <script src=\"../node_modules/chocolat/dist/js/jquery.chocolat.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template JS File -->\r\n");
      out.write("  <script src=\"../assets/js/scripts.js\"></script>\r\n");
      out.write("  <script src=\"../assets/js/custom.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- ajax로 실시간 주가 API데이터 요청 -->\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("     function (){\r\n");
      out.write("    	 $.ajax({\r\n");
      out.write("    		 type: \"get\",\r\n");
      out.write("    		 data: {}\r\n");
      out.write("    		 url: \r\n");
      out.write("    		 dataType:\r\n");
      out.write("    	     sucess:function(response){\r\n");
      out.write("    	    	 consol.log(response)\r\n");
      out.write("    	     }\r\n");
      out.write("    	     error:\r\n");
      out.write("    	 })\r\n");
      out.write("     }\r\n");
      out.write("  \r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
